file = open('lookupfile.txt','w')
file.write('Student 0080')
file.write('\nAverage Score: 79.33')
file.write('\nProgress Score: -1.07')
file.write('\n')
file.write('\nStudent 0096')
file.write('\nAverage Score: 76.67')
file.write('\nProgress Score: 0.00')
file.write('\n')
file.write('\nStudent 0287')
file.write('\nAverage Score: 69.67')
file.write('\nProgress Score: -1.80')
file.write('\n')
file.write('\nStudent 0392')
file.write('\nAverage Score: 87.67')
file.write('\nProgress Score: 0.73')
file.write('\n')
file.write('\nStudent 0457')
file.write('\nAverage Score: 79.33')
file.write('\nProgress Score: 0.43')
file.write('\n')
file.write('\nStudent 0586')
file.write('\nAverage Score: 67.67')
file.write('\nProgress Score: -0.87')
file.write('\n')
file.write('\nStudent 1010')
file.write('\nAverage Score: 87.67')
file.write('\nProgress Score: 2.80')
file.write('\n')
file.write('\nStudent 1026')
file.write('\nAverage Score: 77.67')
file.write('\nProgress Score: 0.53')
file.write('\n')
file.write('\nStudent 1172')
file.write('\nAverage Score: 65.67')
file.write('\nProgress Score: -0.60')
file.write('\n')
file.write('\nStudent 1231')
file.write('\nAverage Score: 74.67')
file.write('\nProgress Score: -0.63')
file.write('\n')
file.write('\nStudent 1515')
file.write('\nAverage Score: 71.00')
file.write('\nProgress Score: -0.57')
file.write('\n')
file.write('\nStudent 1807')
file.write('\nAverage Score: 81.00')
file.write('\nProgress Score: -0.90')
file.write('\n')
file.write('\nStudent 1949')
file.write('\nAverage Score: 61.67')
file.write('\nProgress Score: -0.97')
file.write('\n')
file.write('\nStudent 2189')
file.write('\nAverage Score: 72.67')
file.write('\nProgress Score: -0.93')
file.write('\n')
file.write('\nStudent 2386')
file.write('\nAverage Score: 60.67')
file.write('\nProgress Score: -0.80')
file.write('\n')
file.write('\nStudent 2861')
file.write('\nAverage Score: 83.33')
file.write('\nProgress Score: 0.43')
file.write('\n')
file.write('\nStudent 2965')
file.write('\nAverage Score: 76.67')
file.write('\nProgress Score: 1.43')
file.write('\n')
file.write('\nStudent 3129')
file.write('\nAverage Score: 64.00')
file.write('\nProgress Score: -0.47')
file.write('\n')
file.write('\nStudent 3133')
file.write('\nAverage Score: 76.33')
file.write('\nProgress Score: 0.67')
file.write('\n')
file.write('\nStudent 3692')
file.write('\nAverage Score: 78.67')
file.write('\nProgress Score: 1.20')
file.write('\n')
file.write('\nStudent 3986')
file.write('\nAverage Score: 68.00')
file.write('\nProgress Score: -0.10')
file.write('\n')
file.write('\nStudent 4517')
file.write('\nAverage Score: 65.67')
file.write('\nProgress Score: -1.20')
file.write('\n')
file.write('\nStudent 4644')
file.write('\nAverage Score: 71.00')
file.write('\nProgress Score: -0.17')
file.write('\n')
file.write('\nStudent 4695')
file.write('\nAverage Score: 74.00')
file.write('\nProgress Score: 0.83')
file.write('\n')
file.write('\nStudent 4851')
file.write('\nAverage Score: 88.00')
file.write('\nProgress Score: 0.83')
file.write('\n')
file.write('\nStudent 4900')
file.write('\nAverage Score: 68.67')
file.write('\nProgress Score: -0.67')
file.write('\n')
file.write('\nStudent 5101')
file.write('\nAverage Score: 66.00')
file.write('\nProgress Score: -1.83')
file.write('\n')
file.write('\nStudent 5327')
file.write('\nAverage Score: 62.67')
file.write('\nProgress Score: -1.83')
file.write('\n')
file.write('\nStudent 5665')
file.write('\nAverage Score: 64.33')
file.write('\nProgress Score: -2.30')
file.write('\n')
file.write('\nStudent 5733')
file.write('\nAverage Score: 70.00')
file.write('\nProgress Score: 0.57')
file.write('\n')
file.write('\nStudent 6073')
file.write('\nAverage Score: 76.67')
file.write('\nProgress Score: -0.53')
file.write('\n')
file.write('\nStudent 6472')
file.write('\nAverage Score: 78.33')
file.write('\nProgress Score: -0.53')
file.write('\n')
file.write('\nStudent 6497')
file.write('\nAverage Score: 75.00')
file.write('\nProgress Score: 1.83')
file.write('\n')
file.write('\nStudent 6583')
file.write('\nAverage Score: 79.33')
file.write('\nProgress Score: 0.13')
file.write('\n')
file.write('\nStudent 6727')
file.write('\nAverage Score: 73.33')
file.write('\nProgress Score: 1.30')
file.write('\n')
file.write('\nStudent 6765')
file.write('\nAverage Score: 82.00')
file.write('\nProgress Score: 1.73')
file.write('\n')
file.write('\nStudent 6911')
file.write('\nAverage Score: 69.33')
file.write('\nProgress Score: 0.37')
file.write('\n')
file.write('\nStudent 7459')
file.write('\nAverage Score: 82.00')
file.write('\nProgress Score: 1.23')
file.write('\n')
file.write('\nStudent 7560')
file.write('\nAverage Score: 99.67')
file.write('\nProgress Score: 2.17')
file.write('\n')
file.write('\nStudent 7564')
file.write('\nAverage Score: 83.67')
file.write('\nProgress Score: 0.67')
file.write('\n')
file.write('\nStudent 7717')
file.write('\nAverage Score: 76.67')
file.write('\nProgress Score: 1.20')
file.write('\n')
file.write('\nStudent 7978')
file.write('\nAverage Score: 58.00')
file.write('\nProgress Score: -1.57')
file.write('\n')
file.write('\nStudent 8570')
file.write('\nAverage Score: 68.00')
file.write('\nProgress Score: -1.53')
file.write('\n')
file.write('\nStudent 8616')
file.write('\nAverage Score: 83.33')
file.write('\nProgress Score: 1.67')
file.write('\n')
file.write('\nStudent 9093')
file.write('\nAverage Score: 84.33')
file.write('\nProgress Score: 0.40')
file.write('\n')
file.write('\nStudent 9409')
file.write('\nAverage Score: 67.00')
file.write('\nProgress Score: -0.77')
file.write('\n')
file.write('\nStudent 9725')
file.write('\nAverage Score: 82.67')
file.write('\nProgress Score: 0.73')
file.write('\n')
file.write('\nStudent 9729')
file.write('\nAverage Score: 60.67')
file.write('\nProgress Score: -1.87')
file.close()
